<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transaction Detail - {{ $transaction->transaction_code }}</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 30px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 5px 0;
            font-size: 22px;
        }

        .logo {
            font-size: 18px;
            color: #555;
        }

        .info-table, .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
        }

        .info-table td {
            padding: 5px 0;
        }

        .items-table th, .items-table td {
            border: 1px solid #333;
            padding: 6px;
            text-align: center;
        }

        .items-table th {
            background-color: #f2f2f2;
        }

        .signature {
            margin-top: 40px;
            text-align: right;
        }

        .signature p {
            margin-bottom: 60px;
        }

        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">[Company Logo]</div>
        <h2>APX</h2>
        <p><strong>Transaction Detail</strong></p>
    </div>

    <table class="info-table">
        <tr>
            <td><strong>Transaction Code:</strong></td>
            <td>{{ $transaction->transaction_code }}</td>
        </tr>
        <tr>
            <td><strong>Supplier:</strong></td>
            <td>{{ $transaction->supplier ?? '-' }}</td>
        </tr>
        <tr>
            <td><strong>Contact:</strong></td>
            <td>{{ $transaction->contact ?? '-' }}</td>
        </tr>
        <tr>
            <td><strong>Total Items:</strong></td>
            <td>{{ $transaction->total_items }}</td>
        </tr>
        <tr>
            <td><strong>Total Price:</strong></td>
            <td>Rp {{ number_format($transaction->total_price, 0, ',', '.') }}</td>
        </tr>
        <tr>
            <td><strong>Notes:</strong></td>
            <td>{{ $transaction->notes ?? '-' }}</td>
        </tr>
        <tr>
            <td><strong>Officer:</strong></td>
            <td>{{ $transaction->officer }}</td>
        </tr>
        <tr>
            <td><strong>Transaction Date:</strong></td>
            <td>{{ $transaction->created_at->format('d M Y H:i') }}</td>
        </tr>
    </table>

    <table class="items-table">
    <thead>
        <tr>
            <th>No</th>
            <th>Variant Name</th>
            <th>Batch Number</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->variant->variant_name ?? '-' }}</td>
                <td>{{ $item->batch_number ?? '-' }}</td>
                <td>{{ $item->quantity }}</td>
                <td>Rp {{ number_format($item->price, 0, ',', '.') }}</td>
                <td>Rp {{ number_format($item->subtotal ?? ($item->quantity * $item->price), 0, ',', '.') }}</td>
            </tr>
        @endforeach
    </tbody>
</table>


    <div class="signature">
        <p>Officer,</p>
        <strong><u>{{ $transaction->officer }}</u></strong>
    </div>

    <div class="footer">
        &copy; {{ date('Y') }} APX — Generated by System
    </div>
</body>
</html>
